### ISSUE TITLE
lg-relaunch.py changes

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/interactivespaces-python-api#1]
- ispaces-relaunch.py --full-relaunch should look for ispaces processes that were spawned manually and kill them.
- if no --no-live-activities is specified (meaning - script will try to restart live activities), script needs to do clean tmp + deploy of live activities
- add HTTP timeout to lg-relaunch

**Comment by ezekiel** [comment]
Making lg-relaunch do more is great, but we also need to provide an option to do less. Nobody should be performing a --full-relaunch when peruse activities are simply showing the white-screen initialization race condition.

Stopping and Restarting a particular group should be possible.
```
lg-relaunch --group="FOO"
```

**Comment by ezekiel** [comment]
I have not checked the code, yet - but using the Live Activity, Activity Group, and Spaces metadata during a relaunch will be important to maintain sanity.

lg-relaunch should not simply activate all groups. It should only Start and/or Activate activities/groups which are marked as such via their metadata.

**Comment by mvollrath** [comment]
Running some commands concurrently (batching) will probably make this nicer to work with.  Being more resilient to certain failures (or at least more descriptive about the problem) in the environment might be nice too.

**Comment by axisofentropy** [comment]
Wojtek made some updates:

---

Hi,
I made a lot of improvements to verbosity and logic of lg-relaunch for ispaces. Here are some stats:

ephqdev - 5 controllers:

- live activities relaunch : from 10 to 20secs
- full relaunch - approx. 50-60 secs

gorg-yang - 2 controllers (lgx):
- live activities relaunch: 20-30secs
- full relaunch: ~ 2mins

A lot of stuff is happening asynchronously. Currently the biggest bottlenecks are:
- master shutdown time - 3-5 secs
- master startup time - ~30 seconds
- controller shutdown - 3-5 secs
- controller startup - 5-10 secs

Live activities startup/shutdown time is almost instantaneous.
